delete from Capacities
delete from Iterations
delete from DaysOff
delete from Activities
delete from Members
delete from Members_Teams
delete from teams
delete from Project_AreaPath
delete from RootClassificationNodes
delete from Projects